- name : checking data types
  hosts : loaclhost
  vars :
    NAME : Sivakumar #key value
    Skills : #skills is a list type
    - devops
    - shell
    - ansible
    - linux
  experiences : #map type, it contain key value pairs
    devops : 7
    aws : 6
    docker : 4
  Trainer : true #boolean type
  tasks :
    - name : print key value pair
      ansible.builtin.debug:
      msg : "name:{{NAME}}"
    - name : print list
      ansible.builtin.debug:
      msg : "Skills:{{Skills}}"
      - name : print map
      ansible.builtin.debug:
      msg : "is he trainer:{{Trainer}}"
