- name : loops
  hosts : localhost
  become : yes
  tasks :
  - name : print persons
    ansible.builtin.debug:
    name : {{item}}" 
    state : present #item is default keyword
  loops :
    - git
    - mysql
    - postfix