- name : loops
  hosts : localhost
  become : yes
  tasks :
  - name : install or uninstall packages
    ansible.builtin.package:
    name : "{{item.name}}"
    state : item.state #item is a default keyword
    loops :
      - {name : 'git',state : 'present'}
      - {name : 'mysql',state : 'obsent'}
      - {name : 'postfix',state : 'obsent'}
      - {name : 'nginx',state : 'present'}
      